name: GitHub 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *" # Her gece 00:00'da otomatik oluÅŸturur
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contribution graph
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: emreaygur3   # ðŸ”¥ Eksik olan satÄ±r buydu

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "generated 3D profile" || exit 0
          git push
