name: Generate Tetris Game ðŸŽ®

on:
  schedule:
    - cron: "0 0 * * *" # her gÃ¼n gece 00:00'da otomatik Ã§alÄ±ÅŸÄ±r
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Tetris animation
        uses: marcelinollano/github-tetris@v1
        with:
          github_user_name: emreaygur3
          output: dist/tetris.svg

      - name: Push generated tetris.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
